development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: mysql
  database: rich_cms_test
  username: root
  password: <%= mysql_password %>
  host: 127.0.0.1